# Generated by Django 5.0.6 on 2024-12-10 08:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
