# Generated by Django 5.0.6 on 2024-12-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0003_customer_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
